theme: jekyll-theme-minimal
title: Theoretical Parasites
description: You have reached the website of Turner DeBlieux, and I study theoretical ecology, community ecology, and parasites.
markdown: kramdown
